"""XCP command identifiers — ASAM XCP Part 2, Protocol Layer Specification 1.3."""

# Standard commands
CMD_CONNECT              = 0xFF
CMD_DISCONNECT           = 0xFE
CMD_GET_STATUS           = 0xFD
CMD_SYNCH                = 0xFC
CMD_GET_COMM_MODE_INFO   = 0xFB
CMD_GET_ID               = 0xFA
CMD_SET_REQUEST          = 0xF9
CMD_GET_SEED             = 0xF8
CMD_UNLOCK               = 0xF7
CMD_SET_MTA              = 0xF6
CMD_UPLOAD               = 0xF5
CMD_SHORT_UPLOAD         = 0xF4
CMD_BUILD_CHECKSUM       = 0xF3
CMD_TRANSPORT_LAYER_CMD  = 0xF2
CMD_USER_CMD             = 0xF1

# Calibration commands
CMD_DOWNLOAD             = 0xF0
CMD_DOWNLOAD_NEXT        = 0xEF
CMD_DOWNLOAD_MAX         = 0xEE
CMD_SHORT_DOWNLOAD       = 0xED
CMD_MODIFY_BITS          = 0xEC

# Page commands
CMD_SET_CAL_PAGE         = 0xEB
CMD_GET_CAL_PAGE         = 0xEA
CMD_GET_PAG_PROCESSOR_INFO = 0xE9
CMD_GET_SEGMENT_INFO     = 0xE8
CMD_GET_PAGE_INFO        = 0xE7
CMD_SET_SEGMENT_MODE     = 0xE6
CMD_GET_SEGMENT_MODE     = 0xE5
CMD_COPY_CAL_PAGE        = 0xE4

# DAQ commands
CMD_CLEAR_DAQ_LIST       = 0xE3
CMD_SET_DAQ_PTR          = 0xE2
CMD_WRITE_DAQ            = 0xE1
CMD_SET_DAQ_LIST_MODE    = 0xE0
CMD_GET_DAQ_LIST_MODE    = 0xDF
CMD_START_STOP_DAQ_LIST  = 0xDE
CMD_START_STOP_SYNCH     = 0xDD
CMD_GET_DAQ_CLOCK        = 0xDC
CMD_READ_DAQ             = 0xDB
CMD_GET_DAQ_PROCESSOR_INFO  = 0xDA
CMD_GET_DAQ_RESOLUTION_INFO = 0xD9
CMD_GET_DAQ_LIST_INFO    = 0xD8
CMD_GET_DAQ_EVENT_INFO   = 0xD7
CMD_FREE_DAQ             = 0xD6
CMD_ALLOC_DAQ            = 0xD5
CMD_ALLOC_ODT            = 0xD4
CMD_ALLOC_ODT_ENTRY      = 0xD3

NAMES = {
    CMD_CONNECT: "CONNECT",
    CMD_DISCONNECT: "DISCONNECT",
    CMD_GET_STATUS: "GET_STATUS",
    CMD_SYNCH: "SYNCH",
    CMD_GET_COMM_MODE_INFO: "GET_COMM_MODE_INFO",
    CMD_GET_ID: "GET_ID",
    CMD_SET_MTA: "SET_MTA",
    CMD_UPLOAD: "UPLOAD",
    CMD_SHORT_UPLOAD: "SHORT_UPLOAD",
    CMD_BUILD_CHECKSUM: "BUILD_CHECKSUM",
    CMD_DOWNLOAD: "DOWNLOAD",
    CMD_DOWNLOAD_NEXT: "DOWNLOAD_NEXT",
    CMD_DOWNLOAD_MAX: "DOWNLOAD_MAX",
    CMD_CLEAR_DAQ_LIST: "CLEAR_DAQ_LIST",
    CMD_SET_DAQ_PTR: "SET_DAQ_PTR",
    CMD_WRITE_DAQ: "WRITE_DAQ",
    CMD_SET_DAQ_LIST_MODE: "SET_DAQ_LIST_MODE",
    CMD_GET_DAQ_LIST_MODE: "GET_DAQ_LIST_MODE",
    CMD_START_STOP_DAQ_LIST: "START_STOP_DAQ_LIST",
    CMD_START_STOP_SYNCH: "START_STOP_SYNCH",
    CMD_GET_DAQ_CLOCK: "GET_DAQ_CLOCK",
    CMD_GET_DAQ_PROCESSOR_INFO: "GET_DAQ_PROCESSOR_INFO",
    CMD_GET_DAQ_RESOLUTION_INFO: "GET_DAQ_RESOLUTION_INFO",
    CMD_FREE_DAQ: "FREE_DAQ",
    CMD_ALLOC_DAQ: "ALLOC_DAQ",
    CMD_ALLOC_ODT: "ALLOC_ODT",
    CMD_ALLOC_ODT_ENTRY: "ALLOC_ODT_ENTRY",
}


def name(cmd: int) -> str:
    return NAMES.get(cmd, f"CMD_UNKNOWN(0x{cmd:02X})")
